# fly.toml app configuration file generated for rock-paper-scissor-ws on 2023-10-05T10:34:30+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rock-paper-scissor-ws"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
